name: Scheduled job
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
#    change using crontab.guru
    - cron: '*/5 * * * *'
jobs:
  test:
    name: Run script
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.8' #put your local version
      - name: Install dependencies
        run: pip install bs4 requests dotenv

      - name: Restore previous state
        uses: actions/cache@v4
        with:
          path: state/hashes.json
          key: state-file
          restore-keys: state-file

      - name: Run tests
        run:  python genossenschaftswohung-website-tracker.py

      - name: Save updated state
        uses: actions/cache@v4
        with:
          path: state/hashes.json
          key: state-file
